### ISSUE TITLE
CIFS Option for RPI-3 kernel 5.10 release

### ISSUE THREAD

**Issue by trabant-asb** [pyavitz/rpi-linux#1]
Hi,

I wonder if the 5.10 kernel release packages will still be updated from time to time... currently 5.10.90 is available, i.e. via the fetch tool. If so, could you please change 

`CONFIG_CIFS_POSIX=y`

for the Raspberry Pi 3, just as it is already set in the Pi 4 kernel?

Not having it enabled causes error messages when connecting to a AVM Fritz Box router (recent FritzOS 7.x):

```
[41905.371977] CIFS: VFS: bogus file nlink value 0
[41905.382173] CIFS: VFS: bogus file nlink value 0
[41905.392882] CIFS: VFS: bogus file nlink value 0
[41905.404257] CIFS: VFS: bogus file nlink value 0
[41905.414291] CIFS: VFS: bogus file nlink value 0
[41905.424948] CIFS: VFS: bogus file nlink value 0
[41905.436187] CIFS: VFS: bogus file nlink value 0
[41905.446808] CIFS: VFS: bogus file nlink value 0
[41905.457494] CIFS: VFS: bogus file nlink value 0
[41906.278447] CIFS: VFS: bogus file nlink value 0
[41910.385190] cifs_all_info_to_fattr: 210 callbacks suppressed
```

PS - I am using Devuan Chimaera...

**Comment by pyavitz** [comment]
I moved on to 5.15.y some time ago. I believe the RPF made it the default Sun. or Mon? This usually means the last LTS branch they were using `5.10.y` won't receive any further updates.

As for enabling that module `CONFIG_CIFS_POSIX=y`, no problem. I'll run new builds this evening or tomorrow.

FYI: I suggest opening an [issue](https://github.com/raspberrypi/linux/issues) and asking for it to be included. That will save me from having to shoehorn it on every build.

Thanx.

**Comment by pyavitz** [comment]
Using `fetch` update the kernel. Let me know how it goes.

**Comment by trabant-asb** [comment]
Thanks for taking care... I'm a bit confused though... while the RPF went to 5.15, the Chimaera latest ARM builds are still based on 5.10.95, which is newer than the latest 5.10.90 in this repository. However I will give 5.15 a try and see if it works with my peripherals. 

As for opening an issue with the RPF, I was not aware that you are using their kernel config. I was under the impression that Raspbian uses the _same_ (in my case 64 bit) kernel for all 64bit platforms, be it a Pi 3 or a Pi 4. 

Both my systems were installed using the Chimaera signed releases and upgraded from 5.10.74 to 5.10.90 (from Jan 5th). And while the _CONFIG_CIFS_POSIX_ is set on my Pi 4 desktop, it is not on my headless Pi 3 server. So, the config used for the builds in this repository is _different_ for Pi 3 and Pi 4.

The kernel for me to try out would be _rpi3-5.15.y.tar.xz_, just to be sure?

**Comment by pyavitz** [comment]
The Devuan devs use the builder I maintain to create the IMGs. I'm not officially apart of Devuan. As for `fetch` only showing 5.10.y, update the script.`fetch -u`

I pull the kernel source directly from the RPF github and build it. Whatever defconfig(s) they provided is what I use with little modification. In my looking `CONFIG_CIFS_POSIX` is only enabled on the bcm2711_defconfig. I'm not sure of what the logic is there? Maybe they have a reason, I don't know? But for the time being, I now have the builder look for it and insert it into the defconfig(s) if not found.

You don't need to download the `tarball`. Updating the script `fetch -u`, should resolve the issue of `fetch` not seeing the latest kernel builds.

**Comment by pyavitz** [comment]
Alright, I'm guessing you downloaded from here? https://arm-files.devuan.org/RaspberryPi%20Latest%20Builds/
I also spin IMGs from time to time: https://github.com/pyavitz/binary/releases/tag/images

The diff between what I spin and what they make available:
The `username / passwd` is created on first boot and as a security feature `root` has no password by default. Although that can be easily remedied `sudo passwd root`.

**Comment by trabant-asb** [comment]
Just loaded the 5.15 kernel... the CIFS_Posix option is now set. Thanks for that!
I didn't know that you using the RPI configs, and neither that the creators for the Devuan images build their kernel separately from yours. Good to know...
